### ISSUE TITLE
Duplicated title in the HTML exports for markdown notebooks with title in a first cell with metadata

### ISSUE THREAD

**Issue by nthiery** [jupyter-book/mystmd#1222]
## Description

Assume a jupytext notebook, as in the example below, with title given
in the first markdown cell, and with metadata on that first cell. Then,
as of myst v1.2.3, the title appears twice in the HTML export:

```
---
jupytext:
  text_representation:
    extension: .md
    format_name: myst
    format_version: 0.13
kernelspec:
  display_name: Python 3 (ipykernel)
  language: python
  name: python3
---

+++ {"nbgrader": {"grade": false, "grade_id": "cell-2df857546d357cc2", "locked": true, "schema_version": 3, "solution": false, "task": false}}

# Introduction à la programmation avec Jupyter et Python

## Découvrir Jupyter

...
```

![image](https://github.com/executablebooks/mystmd/assets/545328/ab14c8ca-f5b5-4cfb-a07d-a8e1cd614094)

The duplication vanished when removing the first `+++ ...` line or moving the title in the frontmatter.

Motivation: the metadata here is used to configure the cell for use with nbgrader; in that case to make the cell readonly.

**Comment by stevejpurves** [comment]
@nthiery I beleive also adding `title: null` to the frontmatter will prevent the heading from being "pulled up", although the duplication in the first case is stilll unexpected... @fwkoch?

**Comment by nthiery** [comment]
Thanks for the quick feedback. I tried setting `title: null` in the frontmatter. The duplication is still there. Interestingly enough, the duplication now persists even if there is no cell metadata for the first cell as in:
```
---
jupytext:
  text_representation:
    extension: .md
    format_name: myst
    format_version: 0.13
kernelspec:
  display_name: Python 3 (ipykernel)
  language: python
  name: python3
title: null
---
# Introduction à la programmation avec Jupyter et Python
```

Sounds like just a little logic glitch somewhere.

**Comment by parmentelat** [comment]
I am experiencing this too

**Comment by parmentelat** [comment]
Trying this over again, it seems like the issue appears only when the **title cell is not the first** one in the notebook

**Comment by parmentelat** [comment]
so maybe I jumped to conclusions..

my observation earlier was based on this repo
https://github.com/ue12-p24/intro/tree/myst    
(beware this is not the default branch, as main is still using jb1)
which renders into this
https://ue12-p24.github.io/intro/

all my notebooks used to follow the same scheme: cell#1: licence, cell#2: style, cell#3: title
and with that I had all the titles duplicated

then I tweaked the very first notebook (the one numbered 0-00) to put the 3rd cell first, and after that the welcome page now only has the single title 

this is all jupytext too; maybe you compare with your own builds; \I am not exactly comfortable reporting versioning information about mystmd, except that on my laptop I get 
```
myst --version
v1.2.5
```

but on the github actions side I don't know exacty...

hth

**Comment by nthiery** [comment]
Presumably the difference in what we observed is that the cell holding the title in your case needs no metadata; so your notebook looks like:
```
---
<notebook metadata>
---
# Title
```
while mine looks like:
```
---
<notebook metadata>
---

+++ { cell metadata }
# Title
```

**Comment by parmentelat** [comment]
indeed if I add a tag to my first cell in the notebook that was previously displaying a single title, then the title gets duplicated

so to summarise, the conjecture at this point is that we correctly get a single title iff

- the title comes in the first cell
- and that cell has no metadata

right ?

**Comment by nthiery** [comment]
This sounds right indeed!

**Comment by agoose77** [comment]
I'm pretty sure the title duplication is related to the header lifting logic that we recently reworked. In the new logic, we look for titles only in the first cell IIRC.

**Comment by parmentelat** [comment]
On the other hand, it can't be just that the title is searched only in the first cell, since the title **is found** even when in the third cell:)
It feels more like one part of the system finds the title all right, but then later on some other part fails to find it again (or to remember where it came from in the first place) and then adds it again, right ?

**Comment by parmentelat** [comment]
@stevejpurves 
> I believe also adding title: null to the frontmatter will prevent the heading from being "pulled up", although the duplication in the first case is stilll unexpected... @fwkoch?

from what I can see, setting `title: null` in the frontmatter does not help:

- with no title in the frontmatter, I get the title duplicated
- with `title: Foo`, I get the first (artificially added) title still present but it reads `Foo`
- with `title: null`, I get the same result as with no `title`

**Comment by fwkoch** [comment]
Just catching up on this one - just to clarify what's going on:

We have a function here that messes with titles, maybe more than it should... https://github.com/executablebooks/mystmd/blob/269000cfb41529ee8bd65fe25c209dd4ff4698ff/packages/myst-transforms/src/frontmatter.ts#L32

- If the frontmatter has a title, nothing changes
- If it does not have a title, the first heading is duplicated as title
- If (a) frontmatter title was originally not null, (b) the duplicated heading is depth 1, and (c) the duplicated heading is the next node after the frontmatter, then the heading is removed. Otherwise, it remains.

Looking at the original example in this issue, the metadata adds an extra `block` nesting level, so the structured data becomes
```
type: root
children:
  - type: code
    # this is the yaml frontmatter
  - type: block
    children:
      - type: heading
        # this is the duplicated heading
```
From this, the simple logic no longer thinks that the heading is the "next node" so it is not removed.

I think we should definitely change the logic so the extra block nesting is ignored when determining "heading is next node" - this will be easy.

There's maybe a bigger conversation around this entire title-lifting-and-deleting behavior... it can result in some unexpected consequences.

**Comment by rowanc1** [comment]
cc @Atharva-Rasane who just ran into this as well in the #1379.

**Comment by rowanc1** [comment]
@Atharva-Rasane @nthiery this should be fixed in #1383! Will deploy shortly.

**Comment by nthiery** [comment]
Nice! Will test it next week when I am back from vacations.

Thank you!

**Comment by parmentelat** [comment]
@rowanc1 
as far as I can tell, the issue is still present in release v1.3.4

you can try with this repo here 
https://github.com/ue12-p24/intro/tree/myst
(beware that myst is not the default branch of this repo)

with which I am getting this
https://ue12-p24.github.io/intro/

where all titles are duplicated

**Comment by fwkoch** [comment]
@parmentelat - it makes sense that the issue persists in your examples. MyST now handles a the simple cases of (1) `+++ {"block": "metadata"}` and (2) `<!-- comments -->` above the title, but it still does not handle additional paragraphs/code-cells/etc above the title as in your example.

I think the real fix for this is on the theme side, respecting the computed `content_includes_title` frontmatter flag, as I put in an issue here: https://github.com/jupyter-book/myst-theme/issues/454

For now, if you move the titles above the IPython code cells and the license statements, it will prevent duplication... but that's not very satisfying.
