### ISSUE TITLE
date rendering is a little off

### ISSUE THREAD

**Issue by parmentelat** [jupyter-book/mystmd#1357]
setting a date in the frontmatter results in a date being displayed in all the pages; except that it does not match 

1.2.5

## Description

if I set
```
date: 2024 June
```
I get rendered under the title and authors:
```
May 31, 2024
```

and if I set
```
date: 2024 June 25
```
I get
```
June 24, 2024
```

## Proposed solution

either use the date string as is, or make sure any performed date parsing/conversion does not alter the resulting rendering

## Additional notes

just in case the timezone could matter, my tests were run in Europe in CEST

**Comment by parmentelat** [comment]
and if I say
```
date: 2024
```
I get
```
January 1, 1970
```

**Comment by rowanc1** [comment]
Hm, I thought this was fixed in #607. Can you confirm that your theme is up to date?

```
myst clean --templates
myst start
```

**Comment by parmentelat** [comment]
> myst clean --templates
> myst start

I did that, as well as 

> npm i -g ***@***.***

and now I see

> myst --version
  v1.2.9

and as far as I can tell the problem remains

**Comment by agoose77** [comment]
@parmentelat was this for TeX export? We have identified a bug with date-parsing there.

**Comment by agoose77** [comment]
Crucially, what's happening for (templated) TeX exports:

- We parse the date string as RFC 2822 because it's not in ISO-8601 format
- No timezone is present, so we use the local timezone
- No timestamp is present, so we interpret the time as 00:00
- We then interpret the date in UTC, which applies a reverse timezone transform

For BST=UTC+1, that means "20 Jul 2024" is parsed as:
```node
> new Date("20 Jul 2024")
2024-07-19T23:00:00.000Z
```
where `Z` indicates UTC.

I'll work up a fix.

**Comment by agoose77** [comment]
This is really fiddly from a UX perspective. We need to figure out what the user _actually_ wants.

Most of this complexity comes from using date-times rather than dates (without a time, most dates are "wall time" rather than "exact time" c.f. https://tc39.es/proposal-temporal/docs/ambiguity.html).

So, there are two classes of solution imo:
1. Drop timestamps altogether and talk about wall-time dates
2. Choose a policy for displaying in the _local_ timezone vs UTC

2\. ties the result of the build to the locale of the build system (e.g. myst.yml specifies a TZ-aware timestamp, looks different on different matchines). So that's not ideal in my view.

1\. might be pretty easy; we need to communicate to users that we'll use the timezone of the input you give, which is to say, we drop timezone info.

I'll work up a PR.

**Comment by parmentelat** [comment]
hiya - sorry for the long silence...

to be honest I'm not sure I get why myst bothers at all with any kind of messing about with that date thing

I mean, why not just keep things simple and display the date string as provided by the user 
(or at least provide a means/setting to achieve that) ?

if anything, it would make the "We need to figure out what the user actually wants" thing a no-brainer :)
at least that's what *I*'d want, clearly

"keep it simple", they said ;)

**Comment by agoose77** [comment]
@parmentelat we need to validate and parse dates so that we can present the information structurally to consumers (such as the browser). We'll get this fixed soon!

In the meantime, you can fix this bug by writing your dates as `YYYY-MM-DD`.

**Comment by parmentelat** [comment]
hi @agoose77
this issue is nothing urgent for me, but thanks for the tip :)
