### ISSUE TITLE
Angular brackets in typst

### ISSUE THREAD

**Issue by lorenzo-rovigatti** [jupyter-book/mystmd#1688]
Hi! It looks like the \langle and \rangle math commands don't work with typst. To test it, just try to export to typst this simple equation:

```latex
\langle A \rangle
```

which should give

$$
\langle A \rangle
$$

On my computer (myst 1.3.18, typst 0.12.0) I get these errors:

```
error: unknown variable: langle
   ┌─ _build/temp/mystJryZMx/book_typst.typ:30:2
   │
30 │ $ lang
le a rangle $
   │   ^^^^^^
   │
   = hint: if you meant to display multiple letters as is, try adding spaces between each letter: `l a n g l e`
   = hint: or if you meant to display this as text, try placing it in quotes: `"langle"`


Error: Command failed: typst compile "/tmp/TYPST/_build/temp/mystJryZMx/book_typst.typ"
error: unknown variable: langle
   ┌─ _build/temp/mystJryZMx/book_typst.typ:30:2
   │
30 │ $ langle a rangle $
   │   ^^^^^^
   │
   = hint: if you meant to display multiple letters as is, try adding spaces between each letter: `l a n g l e`
   = hint: or if you meant to display this as text, try placing it in quotes: `"langle"`
```

**Comment by rowanc1** [comment]
This should be fixed in the next release! Thanks again for your help.

**Comment by lorenzo-rovigatti** [comment]
Thanks for the change! Unfortunately I keep getting the same error. I don't know how it works internally, but I noticed that the last tex-to-typst release is 0.0.9, while the commit above references a 0.0.15 version... maybe there is an issue with the version number?

**Comment by lorenzo-rovigatti** [comment]
Hi! I still get the same error with version 1.6.2. Is there anything special I have to do to fix this on my machine?
